[package]
name = "angie3d"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "Toolkit for creating 3DUI applications"
repository = "https://github.com/krre/angie3d"

[dependencies]
